<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

return new class extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->seedFeatures();
    }

    /**
     * 初始化功能数据
     */
    protected function seedFeatures(): void
    {
        $now = time();

        $features = [
            [
                'name' => '查询余额',
                'category' => 'bot',
                'type' => 'command',
                'requestType' => 'message',
                'location' => 'external',
                'feature' => 'YE',
                'description' => '查询大洋支付平台绑定商户的账户余额',
                'handler' => 'GetBalance',
                'config' => '{"command": "/ye", "thridconfig": [2]}',
                'enabled' => 1,
                'creator_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => 0,
            ],
            [
                'name' => '帮助菜单',
                'category' => 'bot',
                'type' => 'command',
                'requestType' => 'message',
                'location' => 'local',
                'feature' => 'BZ',
                'description' => '查看指令使用帮助菜单',
                'handler' => 'CommandHelp',
                'config' => '{"command": "/bz"}',
                'enabled' => 1,
                'creator_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => 0,
            ],
            [
                'name' => '查询订单',
                'category' => 'bot',
                'type' => 'command',
                'requestType' => 'message',
                'location' => 'external',
                'feature' => 'CX',
                'description' => '根据订单号查询指定商户的大洋支付订单',
                'handler' => 'GetOrder',
                'config' => '{"rule": "/^\\\\d+$/", "command": "/cx", "thridconfig": [2]}',
                'enabled' => 1,
                'creator_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => 0,
            ],
            [
                'name' => 'HOOK-卡成功率预警通知',
                'category' => 'bot',
                'type' => 'notify',
                'requestType' => 'message',
                'location' => 'external',
                'feature' => 'HCN',
                'description' => '每隔5分钟推送银行卡成功率通知',
                'handler' => 'HookCardNotify',
                'config' => '{"thridconfig": [1]}',
                'enabled' => 1,
                'creator_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => 0,
            ],
            [
                'name' => '代收补单申请',
                'category' => 'bot',
                'type' => 'command',
                'requestType' => 'message',
                'location' => 'external',
                'feature' => 'BU',
                'description' => '根据订单号和备注码，提交代收订单补单申请',
                'handler' => 'RecoverPaymentOrder',
                'config' => '{"command": "/bu", "paramscount": 2, "thridconfig": [1]}',
                'enabled' => 1,
                'creator_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => 0,
            ],
            [
                'name' => '代付订单二次确认',
                'category' => 'bot',
                'type' => 'interaction',
                'requestType' => 'callback_query',
                'location' => 'external',
                'feature' => 'TOP',
                'description' => '推送需要二次确认的代付订单，通过操作"确认提交"和"拒绝提交"完成审核',
                'handler' => 'TransferOrderPush',
                'config' => '{"thridconfig": [5, 3]}',
                'enabled' => 1,
                'creator_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => 0,
            ],
            [
                'name' => '越南识图-代收补单',
                'category' => 'bot',
                'type' => 'ocr',
                'requestType' => 'message',
                'location' => 'external',
                'feature' => 'VN_OCR',
                'description' => '识别越南支付付款截图，提取关键信息提交到HOOK进行补单申请',
                'handler' => 'PaymentVnOcr',
                'config' => '{"thridconfig": [1, 6]}',
                'enabled' => 1,
                'creator_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => 0,
            ],
            [
                'name' => '泰国识图_代收补单',
                'category' => 'bot',
                'type' => 'ocr',
                'requestType' => 'message',
                'location' => 'external',
                'feature' => 'TH_OCR',
                'description' => '识别泰国支付付款截图，提取关键信息提交到HOOK进行补单申请',
                'handler' => 'PaymentThOcr',
                'config' => '{"thridconfig": [1, 6]}',
                'enabled' => 1,
                'creator_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => 0,
            ],
            [
                'name' => 'USDT识图_代收补单',
                'category' => 'bot',
                'type' => 'ocr',
                'requestType' => 'message',
                'location' => 'external',
                'feature' => 'USDT_OCR',
                'description' => '识别USDT支付付款截图，提取关键信息提交到HOOK进行补单申请',
                'handler' => 'PaymentUsdtOcr',
                'config' => '{"thridconfig": [1, 6]}',
                'enabled' => 1,
                'creator_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => 0,
            ],
            [
                'name' => '群内代付支付',
                'category' => 'bot',
                'type' => 'interaction',
                'requestType' => 'callback_query',
                'location' => 'external',
                'feature' => 'HTOPG',
                'description' => 'HOOK推送未支付代付订单到群内，管理员绑定银行卡和身份后即可操作扫二维码付款并设置成"成功" 或 未支付设置成"失败"',
                'handler' => 'HookTransferOrderPayGroup',
                'config' => '{"thridconfig": [1]}',
                'enabled' => 1,
                'creator_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => 0,
            ],
            [
                'name' => '消息群发',
                'category' => 'realMan',
                'type' => 'notify',
                'requestType' => 'message',
                'location' => 'local',
                'feature' => 'SMTG',
                'description' => '发送消息到指定群，可多选',
                'handler' => 'SendMsgToGroups',
                'config' => '{}',
                'enabled' => 1,
                'creator_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => 0,
            ],
            [
                'name' => '消息私发',
                'category' => 'realMan',
                'type' => 'notify',
                'requestType' => 'message',
                'location' => 'local',
                'feature' => 'SMTP',
                'description' => '给群内的个人发送消息(私聊单独窗口)',
                'handler' => 'SendMsgToPerson',
                'config' => '{}',
                'enabled' => 1,
                'creator_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => 0,
            ],
            [
                'name' => '消息群内@发送',
                'category' => 'realMan',
                'type' => 'notify',
                'requestType' => 'message',
                'location' => 'local',
                'feature' => 'SMTGP',
                'description' => '发送消息到群内，并指定@群员',
                'handler' => 'SendMsgToGroupPerson',
                'config' => '{}',
                'enabled' => 1,
                'creator_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => 0,
            ],
            [
                'name' => '快捷回复',
                'category' => 'realMan',
                'type' => 'notify',
                'requestType' => 'message',
                'location' => 'local',
                'feature' => 'FRM',
                'description' => '匹配关键词，进行快捷回复',
                'handler' => 'FastReplayMsg',
                'config' => '{}',
                'enabled' => 1,
                'creator_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => 0,
            ],
            [
                'name' => '踢除群员',
                'category' => 'realMan',
                'type' => 'notify',
                'requestType' => 'message',
                'location' => 'local',
                'feature' => 'KOG',
                'description' => '将指定群员踢除出群，机器人需admin身份且有全部权限',
                'handler' => 'KickOutGroup',
                'config' => '{}',
                'enabled' => 1,
                'creator_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => 0,
            ],
            [
                'name' => '记账',
                'category' => 'bot',
                'type' => 'command',
                'requestType' => 'message',
                'location' => 'local',
                'feature' => 'FN',
                'description' => '使用后，群内可以使用记账功能进行账务登记',
                'handler' => 'FinanceNote',
                'config' => '{}',
                'enabled' => 0,
                'creator_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => 0,
            ],
            [
                'name' => '查看大洋支付文档',
                'category' => 'bot',
                'type' => 'command',
                'requestType' => 'message',
                'location' => 'local',
                'feature' => 'GDYPDP',
                'description' => '输入指令，推送大洋支付文档链接',
                'handler' => 'GetDaYangPayDocPath',
                'config' => '{"command": "/dydoc", "paramscount": 0}',
                'enabled' => 1,
                'creator_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => 0,
            ],
            [
                'name' => '生成代收/代付提交参数和签名参数以及签名串',
                'category' => 'bot',
                'type' => 'command',
                'requestType' => 'message',
                'location' => 'local',
                'feature' => 'CDD',
                'description' => '生成代收/代付提交参数和签名参数以及签名串，便于大洋支付下游参考开发；指令参数 p 获取代收，指令参数 t 获取代付。',
                'handler' => 'CreateDevlopData',
                'config' => '{"command": "/cdd", "paramscount": 1}',
                'enabled' => 1,
                'creator_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => 0,
            ],
            [
                'name' => '大洋支付测试代收回调',
                'category' => 'bot',
                'type' => 'command',
                'requestType' => 'message',
                'location' => 'external',
                'feature' => 'ACBP',
                'description' => '群绑定商户ID后，输入指令加订单号参数，自助回调；仅支持大洋原生支付。',
                'handler' => 'AutoCallBackPayment',
                'config' => '{"command": "/acbp", "paramscount": 1, "thridconfig": [3]}',
                'enabled' => 0,
                'creator_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => 0,
            ],
            [
                'name' => '大洋支付测试代付回调',
                'category' => 'bot',
                'type' => 'command',
                'requestType' => 'message',
                'location' => 'external',
                'feature' => 'ACBT',
                'description' => '群绑定商户ID，输入指令和参数：订单号，参数：s/f（s表示回调代付成功，f表示回调代付失败）  ,自助回调；  例如： /acbt 20112312 s',
                'handler' => 'AutoCallBackTransfer',
                'config' => '{"command": "/acbt", "paramscount": 2, "thridconfig": [3]}',
                'enabled' => 0,
                'creator_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => 0,
            ],
            [
                'name' => '人工通道',
                'category' => 'bot',
                'type' => 'command',
                'requestType' => 'message',
                'location' => 'local',
                'feature' => 'RG',
                'description' => '输入指令，机器人会@群内指定的人工客服。',
                'handler' => 'ArtificialChannel',
                'config' => '{"command": "/rg"}',
                'enabled' => 1,
                'creator_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => 0,
            ],
            [
                'name' => '回调订单',
                'category' => 'bot',
                'type' => 'command',
                'requestType' => 'message',
                'location' => 'external',
                'feature' => 'HT',
                'description' => '使用商户订单号或订单号，回调商户订单',
                'handler' => 'DaYangRecover',
                'config' => '{"command": "/ht", "paramscount": 1, "thridconfig": [3]}',
                'enabled' => 1,
                'creator_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => 0,
            ],
            [
                'name' => '表情包采集',
                'category' => 'realMan',
                'type' => 'interaction',
                'requestType' => 'message',
                'location' => 'local',
                'feature' => 'CEMOJ',
                'description' => '采集指定群发送的表情包，在后续群发消息中使用',
                'handler' => 'CollectEmojiFromGroup',
                'config' => '{}',
                'enabled' => 1,
                'creator_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => 0,
            ],
        ];

        // 插入数据，使用 updateOrInsert 避免重复
        foreach ($features as $feature) {
            DB::table('features')->updateOrInsert(
                ['feature' => $feature['feature']],
                $feature
            );
        }
    }
};
