<?php

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

return new class extends Seeder
{
    /**
     * Run the seeder.
     *
     * @return void
     */
    public function run(): void
    {
        $menus = $this->menus();

        importTreeData($menus, 'permissions');
    }

    public function menus(): array
    {
        return array (
  0 => 
  array (
    'id' => 37,
    'parent_id' => 0,
    'permission_name' => '号码采集',
    'route' => '/collect',
    'icon' => 'book-open',
    'module' => 'telegram',
    'permission_mark' => '',
    'component' => '/layout/index.vue',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 1,
    'hidden' => 1,
    'sort' => 1,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759231946,
    'updated_at' => 1759232545,
    'deleted_at' => 0,
  ),
  1 => 
  array (
    'id' => 63,
    'parent_id' => 0,
    'permission_name' => '附加功能',
    'route' => '/activity',
    'icon' => 'briefcase',
    'module' => 'telegram',
    'permission_mark' => '',
    'component' => '/telegram/features/index.vue',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 1,
    'hidden' => 1,
    'sort' => 1,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759689309,
    'updated_at' => 1765180324,
    'deleted_at' => 0,
  ),
  2 => 
  array (
    'id' => 108,
    'parent_id' => 0,
    'permission_name' => '机器人管理',
    'route' => '/telegram',
    'icon' => 'adjustments-horizontal',
    'module' => 'telegram',
    'permission_mark' => '',
    'component' => '/layout/index.vue',
    'redirect' => NULL,
    'keepalive' => 1,
    'type' => 1,
    'hidden' => 1,
    'sort' => 1,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1766561837,
    'updated_at' => 1766561837,
    'deleted_at' => 0,
  ),
  3 => 
  array (
    'id' => 84,
    'parent_id' => 64,
    'permission_name' => '删除',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'activitys@destroy',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 5,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759689435,
    'updated_at' => 1759689435,
    'deleted_at' => 0,
  ),
  4 => 
  array (
    'id' => 80,
    'parent_id' => 64,
    'permission_name' => '列表',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'activitys@index',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 1,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759689435,
    'updated_at' => 1759689435,
    'deleted_at' => 0,
  ),
  5 => 
  array (
    'id' => 82,
    'parent_id' => 64,
    'permission_name' => '读取',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'activitys@show',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 3,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759689435,
    'updated_at' => 1759689435,
    'deleted_at' => 0,
  ),
  6 => 
  array (
    'id' => 81,
    'parent_id' => 64,
    'permission_name' => '新增',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'activitys@store',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 2,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759689435,
    'updated_at' => 1759689435,
    'deleted_at' => 0,
  ),
  7 => 
  array (
    'id' => 83,
    'parent_id' => 64,
    'permission_name' => '更新',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'activitys@update',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 4,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759689435,
    'updated_at' => 1759689435,
    'deleted_at' => 0,
  ),
  8 => 
  array (
    'id' => 59,
    'parent_id' => 108,
    'permission_name' => '群分组',
    'route' => 'groupgroups',
    'icon' => 'folder',
    'module' => 'telegram',
    'permission_mark' => 'botGroupGroup',
    'component' => '/telegram/botGroupGroup/index.vue',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 2,
    'hidden' => 1,
    'sort' => 1,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759688951,
    'updated_at' => 1766561617,
    'deleted_at' => 0,
  ),
  9 => 
  array (
    'id' => 102,
    'parent_id' => 59,
    'permission_name' => '删除',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'botGroupGroup@destroy',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 5,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1761826367,
    'updated_at' => 1761826367,
    'deleted_at' => 0,
  ),
  10 => 
  array (
    'id' => 99,
    'parent_id' => 59,
    'permission_name' => '列表',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'botGroupGroup@index',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 1,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1761826367,
    'updated_at' => 1761826367,
    'deleted_at' => 0,
  ),
  11 => 
  array (
    'id' => 100,
    'parent_id' => 59,
    'permission_name' => '读取',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'botGroupGroup@show',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 3,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1761826367,
    'updated_at' => 1761826367,
    'deleted_at' => 0,
  ),
  12 => 
  array (
    'id' => 98,
    'parent_id' => 59,
    'permission_name' => '新增',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'botGroupGroup@store',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 1,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1761826362,
    'updated_at' => 1766561216,
    'deleted_at' => 0,
  ),
  13 => 
  array (
    'id' => 101,
    'parent_id' => 59,
    'permission_name' => '更新',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'botGroupGroup@update',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 4,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1761826367,
    'updated_at' => 1761826367,
    'deleted_at' => 0,
  ),
  14 => 
  array (
    'id' => 61,
    'parent_id' => 108,
    'permission_name' => '群列表',
    'route' => 'groups',
    'icon' => 'home',
    'module' => 'telegram',
    'permission_mark' => 'botGroups',
    'component' => '/telegram/botGroups/index.vue',
    'redirect' => NULL,
    'keepalive' => 1,
    'type' => 2,
    'hidden' => 1,
    'sort' => 1,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759689166,
    'updated_at' => 1759689166,
    'deleted_at' => 0,
  ),
  15 => 
  array (
    'id' => 74,
    'parent_id' => 61,
    'permission_name' => '删除',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'botGroups@destroy',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 5,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759689431,
    'updated_at' => 1759689431,
    'deleted_at' => 0,
  ),
  16 => 
  array (
    'id' => 70,
    'parent_id' => 61,
    'permission_name' => '列表',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'botGroups@index',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 1,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759689431,
    'updated_at' => 1759689431,
    'deleted_at' => 0,
  ),
  17 => 
  array (
    'id' => 72,
    'parent_id' => 61,
    'permission_name' => '读取',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'botGroups@show',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 3,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759689431,
    'updated_at' => 1759689431,
    'deleted_at' => 0,
  ),
  18 => 
  array (
    'id' => 71,
    'parent_id' => 61,
    'permission_name' => '新增',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'botGroups@store',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 2,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759689431,
    'updated_at' => 1759689431,
    'deleted_at' => 0,
  ),
  19 => 
  array (
    'id' => 73,
    'parent_id' => 61,
    'permission_name' => '更新',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'botGroups@update',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 4,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759689431,
    'updated_at' => 1759689431,
    'deleted_at' => 0,
  ),
  20 => 
  array (
    'id' => 60,
    'parent_id' => 108,
    'permission_name' => '机器人列表',
    'route' => 'bots',
    'icon' => 'wrench-screwdriver',
    'module' => 'telegram',
    'permission_mark' => 'bots',
    'component' => '/telegram/bots/index.vue',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 2,
    'hidden' => 1,
    'sort' => 1,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759689076,
    'updated_at' => 1759689094,
    'deleted_at' => 0,
  ),
  21 => 
  array (
    'id' => 79,
    'parent_id' => 60,
    'permission_name' => '删除',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'bots@destroy',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 5,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759689433,
    'updated_at' => 1759689433,
    'deleted_at' => 0,
  ),
  22 => 
  array (
    'id' => 75,
    'parent_id' => 60,
    'permission_name' => '列表',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'bots@index',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 1,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759689433,
    'updated_at' => 1759689433,
    'deleted_at' => 0,
  ),
  23 => 
  array (
    'id' => 77,
    'parent_id' => 60,
    'permission_name' => '读取',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'bots@show',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 3,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759689433,
    'updated_at' => 1759689433,
    'deleted_at' => 0,
  ),
  24 => 
  array (
    'id' => 76,
    'parent_id' => 60,
    'permission_name' => '新增',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'bots@store',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 2,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759689433,
    'updated_at' => 1759689433,
    'deleted_at' => 0,
  ),
  25 => 
  array (
    'id' => 78,
    'parent_id' => 60,
    'permission_name' => '更新',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'bots@update',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 4,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759689433,
    'updated_at' => 1759689433,
    'deleted_at' => 0,
  ),
  26 => 
  array (
    'id' => 64,
    'parent_id' => 63,
    'permission_name' => '功能列表',
    'route' => 'funs',
    'icon' => 'paper-airplane',
    'module' => 'telegram',
    'permission_mark' => 'features',
    'component' => '/telegram/features/index.vue',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 2,
    'hidden' => 1,
    'sort' => 1,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759689425,
    'updated_at' => 1765180360,
    'deleted_at' => 0,
  ),
  27 => 
  array (
    'id' => 38,
    'parent_id' => 37,
    'permission_name' => '号码仓库',
    'route' => 'phone',
    'icon' => 'folder',
    'module' => 'telegram',
    'permission_mark' => 'phone',
    'component' => '/telegram/phone/index.vue',
    'redirect' => NULL,
    'keepalive' => 1,
    'type' => 2,
    'hidden' => 1,
    'sort' => 1,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759232040,
    'updated_at' => 1759232040,
    'deleted_at' => 0,
  ),
  28 => 
  array (
    'id' => 55,
    'parent_id' => 38,
    'permission_name' => '删除',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'phone@destroy',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 5,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759232198,
    'updated_at' => 1759232198,
    'deleted_at' => 0,
  ),
  29 => 
  array (
    'id' => 58,
    'parent_id' => 38,
    'permission_name' => '下载模板',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'phone@downloadPhoneTemplate',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 1,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759232652,
    'updated_at' => 1759232652,
    'deleted_at' => 0,
  ),
  30 => 
  array (
    'id' => 57,
    'parent_id' => 38,
    'permission_name' => '导出',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'phone@export',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 8,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759232198,
    'updated_at' => 1759232198,
    'deleted_at' => 0,
  ),
  31 => 
  array (
    'id' => 56,
    'parent_id' => 38,
    'permission_name' => '导入',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'phone@import',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 6,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759232198,
    'updated_at' => 1759232198,
    'deleted_at' => 0,
  ),
  32 => 
  array (
    'id' => 51,
    'parent_id' => 38,
    'permission_name' => '列表',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'phone@index',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 1,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759232198,
    'updated_at' => 1759232198,
    'deleted_at' => 0,
  ),
  33 => 
  array (
    'id' => 53,
    'parent_id' => 38,
    'permission_name' => '读取',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'phone@show',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 3,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759232198,
    'updated_at' => 1759232198,
    'deleted_at' => 0,
  ),
  34 => 
  array (
    'id' => 52,
    'parent_id' => 38,
    'permission_name' => '新增',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'phone@store',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 2,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759232198,
    'updated_at' => 1759232198,
    'deleted_at' => 0,
  ),
  35 => 
  array (
    'id' => 54,
    'parent_id' => 38,
    'permission_name' => '更新',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'phone@update',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 4,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759232198,
    'updated_at' => 1759232198,
    'deleted_at' => 0,
  ),
  36 => 
  array (
    'id' => 39,
    'parent_id' => 37,
    'permission_name' => '扫描记录',
    'route' => 'sCanLog',
    'icon' => 'clipboard-document-list',
    'module' => 'telegram',
    'permission_mark' => 'sCanLog',
    'component' => '/telegram/sCanLog/index.vue',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 2,
    'hidden' => 1,
    'sort' => 1,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759232104,
    'updated_at' => 1759232193,
    'deleted_at' => 0,
  ),
  37 => 
  array (
    'id' => 50,
    'parent_id' => 39,
    'permission_name' => '删除',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'sCanLog@destroy',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 5,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759232197,
    'updated_at' => 1759232197,
    'deleted_at' => 0,
  ),
  38 => 
  array (
    'id' => 46,
    'parent_id' => 39,
    'permission_name' => '列表',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'sCanLog@index',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 1,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759232197,
    'updated_at' => 1759232197,
    'deleted_at' => 0,
  ),
  39 => 
  array (
    'id' => 48,
    'parent_id' => 39,
    'permission_name' => '读取',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'sCanLog@show',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 3,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759232197,
    'updated_at' => 1759232197,
    'deleted_at' => 0,
  ),

  45 => 
  array (
    'id' => 92,
    'parent_id' => 63,
    'permission_name' => '三方配置',
    'route' => 'tconf',
    'icon' => 'cog-6-tooth',
    'module' => 'telegram',
    'permission_mark' => 'thridConfig',
    'component' => '/telegram/thridConfig/index.vue',
    'redirect' => NULL,
    'keepalive' => 1,
    'type' => 2,
    'hidden' => 1,
    'sort' => 1,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1760101751,
    'updated_at' => 1760101751,
    'deleted_at' => 0,
  ),
  46 => 
  array (
    'id' => 97,
    'parent_id' => 92,
    'permission_name' => '删除',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'thridConfig@destroy',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 5,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1760101756,
    'updated_at' => 1760101756,
    'deleted_at' => 0,
  ),
  47 => 
  array (
    'id' => 93,
    'parent_id' => 92,
    'permission_name' => '列表',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'thridConfig@index',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 1,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1760101756,
    'updated_at' => 1760101756,
    'deleted_at' => 0,
  ),
  48 => 
  array (
    'id' => 95,
    'parent_id' => 92,
    'permission_name' => '读取',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'thridConfig@show',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 3,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1760101756,
    'updated_at' => 1760101756,
    'deleted_at' => 0,
  ),
  49 => 
  array (
    'id' => 94,
    'parent_id' => 92,
    'permission_name' => '新增',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'thridConfig@store',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 2,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1760101756,
    'updated_at' => 1760101756,
    'deleted_at' => 0,
  ),
  50 => 
  array (
    'id' => 96,
    'parent_id' => 92,
    'permission_name' => '更新',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'thridConfig@update',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 4,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1760101756,
    'updated_at' => 1760101756,
    'deleted_at' => 0,
  ),
  51 => 
  array (
    'id' => 40,
    'parent_id' => 37,
    'permission_name' => '账号仓库',
    'route' => 'telegramApiUser',
    'icon' => 'circle-stack',
    'module' => 'telegram',
    'permission_mark' => 'telegramApiUser',
    'component' => '/telegram/telegramApiUser/index.vue',
    'redirect' => NULL,
    'keepalive' => 1,
    'type' => 2,
    'hidden' => 1,
    'sort' => 1,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759232185,
    'updated_at' => 1759232185,
    'deleted_at' => 0,
  ),
  52 => 
  array (
    'id' => 45,
    'parent_id' => 40,
    'permission_name' => '删除',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'telegramApiUser@destroy',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 5,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759232195,
    'updated_at' => 1759232195,
    'deleted_at' => 0,
  ),
  53 => 
  array (
    'id' => 41,
    'parent_id' => 40,
    'permission_name' => '列表',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'telegramApiUser@index',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 1,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759232195,
    'updated_at' => 1759232195,
    'deleted_at' => 0,
  ),
  54 => 
  array (
    'id' => 43,
    'parent_id' => 40,
    'permission_name' => '读取',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'telegramApiUser@show',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 3,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759232195,
    'updated_at' => 1759232195,
    'deleted_at' => 0,
  ),
  55 => 
  array (
    'id' => 42,
    'parent_id' => 40,
    'permission_name' => '新增',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'telegramApiUser@store',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 2,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759232195,
    'updated_at' => 1759232195,
    'deleted_at' => 0,
  ),
  56 => 
  array (
    'id' => 44,
    'parent_id' => 40,
    'permission_name' => '更新',
    'route' => '',
    'icon' => '',
    'module' => 'telegram',
    'permission_mark' => 'telegramApiUser@update',
    'component' => '',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 3,
    'hidden' => 1,
    'sort' => 4,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => 1759232195,
    'updated_at' => 1759232195,
    'deleted_at' => 0,
  ),
);
    }
};
